# Generated by Django 5.0.6 on 2024-07-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='enquiry_no',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
